In [2]:
import numpy as np

In [3]:
list_1 = [1,2,3,4,5,6,7,8,9]

We convert our list into an array

In [4]:
array = np.array(list_1)

A matrix are several `vectors` o `lists` stacked one over other

In [5]:
type(array)
print(array)

[1 2 3 4 5 6 7 8 9]


In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix_np = np.array(matrix)
matrix_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`Indexing` allows us to access each array/matrix element

In [10]:
print(array[0])
print(matrix_np[0,0], matrix_np[2,2])

1
1 9


In [12]:
result = array[2] + matrix_np[2,2]
result

12

We can use `slicing` for pulling our key data out from dataset, in the following case we can extract all data in array. Same `slicing` used in Python lists apply on this:

In [17]:
array[1:6] #from position 1 to 5

array([2, 3, 4, 5, 6])

In [15]:
array[:6] #all array, from position 0 to 5

array([1, 2, 3, 4, 5, 6])

In [16]:
array[::3] #from the beginning to the end of the array, incrementing the index by three in each step.

array([1, 4, 7])

Accessing a matrix, we need point our n-row and m-column of the matrix. For instance, if we want to pull out the data inside first row and second column, we indicate the following command:

In [20]:
print(matrix_np)
matrix_np[0, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

#### Challenge 1
Create a 3D matrix!

In [23]:
matrix_3d = [[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]], [[19,20,21], [22,23,24], [25,26,27]]]
matrix_3d_np = np.array(matrix_3d)
matrix_3d_np

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [24]:
dimensions = matrix_3d_np.shape
dimensions

(3, 3, 3)