In [35]:
import numpy as np

We can know array data type searching for `.dtype` property.

In [36]:
array = np.array([0,1,2,3,4,-1])
array.dtype

dtype('int64')

We can change data type in our array in an easy way, redefine in array() declaration

In [37]:
array = np.array([0,1,2,3,4,-1], dtype= 'float64')
array.dtype

dtype('float64')

In [38]:
array

array([ 0.,  1.,  2.,  3.,  4., -1.])

If we have our defined array through np.array() method, we can reset datatype through `.astype()`

In [39]:
array

array([ 0.,  1.,  2.,  3.,  4., -1.])

In [40]:
array = array.astype(np.int_)
array

array([ 0,  1,  2,  3,  4, -1])

Also, we can convert our array into bolean data types using same method. In this case, `False` will be equal to 0, and `True` will be equal to any other int number.

In [41]:
array = array.astype(np.bool_)
array

array([False,  True,  True,  True,  True,  True])

Also, we can transform data into `string` data types.

In [46]:
array = np.array([0,1,2,3,4,-1])
array = array.astype(np.string_)
array

array([b'0', b'1', b'2', b'3', b'4', b'-1'], dtype='|S21')

And we can retransform them into int numbers, again...

In [47]:
array = array.astype(np.int8)
array

array([ 0,  1,  2,  3,  4, -1], dtype=int8)

Of course, we can't transform a non-number string into number data types, a `ValueError` will be raised.

In [48]:
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'