In [24]:
import numpy as np

Scalars are arrays with just one single value, which dimensionality is equal to zero.

In [25]:
scalar = np.array(42)
print(scalar)
print(f'Dimension of scalar is {scalar.ndim}')

42
Dimension of scalar is 0


Vectors are 1xn matrices, consisted of a single row with n elements as a Python list.

In [26]:
vector = np.array([1,2,3])
print(vector)
print(f'Dimension of vector is {vector.ndim}')

[1 2 3]
Dimension of vector is 1


Matrices are mxn arrays of elements, consisted of m rows and n columns. Those datasets are quite common in data analysis, we can find them in Excel spreadsheets.

In [27]:
matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(matrix)
print(f'Dimension of matrix is {matrix.ndim}')

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension of matrix is 2


Tensors can be defined as a multidimensional array or data structure. Extends the concept of matrices to more than two dimensions, a generalization of matrices to an arbitrary number of dimensions (arrays with n dimensions). In the image, we can illustrate events in a timeline using 3D tensors, where (x = events, y = features, z = time)

<div style="text-align: center;">
    <img src="./imgs/tensor_example.png" alt="Alt Text" width="400" height="200">
</div>

In [28]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
print(f'Dimension of tensor is {tensor.ndim}')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
Dimension of tensor is 3


#### `Adding or removing dimensions`

We can define dimensionality n from array defining as we can observe below

In [29]:
vector = np.array([1,2,3], ndmin = 10)
print(vector)
print(f'Dimension of the vector is {vector.ndim}')

[[[[[[[[[[1 2 3]]]]]]]]]]
Dimension of the vector is 10


Dimensions can be expanded in existing arrays using ``expand_dims()``. 
Axis = 0 refers to rows, while axis = 1 refers to columns.

In [30]:
expand = np.expand_dims(np.array([1,2,3,4]), axis = 0)
print(expand)
expand.ndim

[[1 2 3 4]]


2

Also, we can remove or zip unused dimensions in the array.

In [31]:
print(vector, f', our current dimension is {vector.ndim}')
vector_redim = np.squeeze(vector)
print(vector_redim, f', our current dimension is {vector_redim.ndim}')

[[[[[[[[[[1 2 3]]]]]]]]]] , our current dimension is 10
[1 2 3] , our current dimension is 1


#### `Challenge No. 2`

1. Define a 5D tensor
2. Add a new dimension in any axis
3. Delete all unused dimensions

In [40]:
#define a 5D tensor

tensor_5d = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]], ndmin=5)
print(tensor_5d)
print(f'Dimensionality of tensor_5d is {tensor_5d.ndim}')



[[[[[1 0 0 0 0]
    [0 1 0 0 0]
    [0 0 1 0 0]
    [0 0 0 1 0]
    [0 0 0 0 1]]]]]
Dimensionality of tensor_5d is 5


In [42]:
#add a new column
tensor_5d_redim = np.expand_dims(tensor_5d, axis=1)
print(tensor_5d_redim)
print(f'Dimensionality of tensor_5d_redim is {tensor_5d_redim.ndim}')

[[[[[[1 0 0 0 0]
     [0 1 0 0 0]
     [0 0 1 0 0]
     [0 0 0 1 0]
     [0 0 0 0 1]]]]]]
Dimensionality of tensor_5d_redim is 6


In [43]:
#remove unused dimensions

print(tensor_5d_redim, f', our current dimension is {tensor_5d_redim.ndim}')
tensor_sq = np.squeeze(tensor_5d_redim)
print(tensor_sq, f', our current dimension is {tensor_sq.ndim}')

[[[[[[1 0 0 0 0]
     [0 1 0 0 0]
     [0 0 1 0 0]
     [0 0 0 1 0]
     [0 0 0 0 1]]]]]] , our current dimension is 6
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] , our current dimension is 2
