In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

`np.arange()` method can provide an array from a range as the list created above.

In [42]:
np.arange(start = 0, stop = 20, step = 2) #in steps of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.random.rand()

0.3475066277583212

In [48]:
np.random.rand(4,4)

array([[0.53343017, 0.95881421, 0.47628746, 0.92098421],
       [0.60175755, 0.19808386, 0.94725324, 0.03226535],
       [0.25947336, 0.35279579, 0.61621251, 0.17555369],
       [0.1037613 , 0.48407524, 0.38805642, 0.7372308 ]])

In [49]:
np.random.randint(1,15) #could be useful for neural networks

6

In [50]:
np.random.randint(1,100, (10,10))

array([[45,  4, 96, 34, 94, 16, 62, 63, 96, 16],
       [68, 19, 40, 79, 73, 80, 85, 45, 39, 23],
       [47, 55, 72, 79, 75, 66, 59, 84,  7, 19],
       [63, 72, 87, 28, 21,  6, 88, 62, 47, 50],
       [85, 71, 71, 44, 34, 68, 89, 94, 60, 98],
       [ 9, 55, 60, 53, 81, 12, 60, 53, 30, 24],
       [61, 73, 25, 69,  3, 28, 77, 42, 61, 48],
       [ 4, 72, 48, 40, 77, 99, 93, 15, 94, 76],
       [95, 70, 47, 10, 96, 78,  3, 79, 39, 70],
       [65,  5, 31, 79, 48, 93, 73,  2, 29,  9]])

In [51]:
np.full((3,3), 0, dtype=bool, order='c')

array([[False, False, False],
       [False, False, False],
       [False, False, False]])