In [3]:
import numpy as np

Conditions allow us to perform more specific searches.

In [8]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

When we request a condition, a boolean array is retrieved where condition is kept to.

In [9]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Returns value where condition is True

In [10]:
arr[cond_index]

array([ 6,  7,  8,  9, 10], dtype=int8)

In the following case, we have multiple conditions. Create an array where numbers are between 5 and 9 from original `arr`

In [11]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Or, modifying values that satisfy a condition.

In [13]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)