In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape

[[4 8]
 [9 1]
 [9 3]]


(3, 2)

#### `Reshape`
Transforms arrays while total elements are conserved.

In [3]:
arr.reshape(1,6)

array([[4, 8, 9, 1, 9, 3]])

In [4]:
arr.reshape(2,3)

array([[4, 8, 9],
       [1, 9, 3]])

In [5]:
np.reshape(arr, (2,3))

array([[4, 8, 9],
       [1, 9, 3]])

C based reshape method reorder arrays into a new dimension, taking each element out by row.

In [6]:
np.reshape(arr, (2,3), 'C')

array([[4, 8, 9],
       [1, 9, 3]])

Fortran based reshape method reorder arrays into a new dimension, taking each element out by column.

In [7]:
print(arr)
np.reshape(arr, (2,3), 'F')

[[4 8]
 [9 1]
 [9 3]]


array([[4, 9, 1],
       [9, 8, 3]])

Also, exists optimized memory reshape according to our machine requirements, in our case is like C did it.

In [8]:
np.reshape(arr, (2,3), 'A')

array([[4, 8, 9],
       [1, 9, 3]])

#### `Challenge 3`
* Create any array and change its dimensions.
* Try to change array's shape in a way that original structure is not preserved.

In [9]:
challenge = np.random.randint(1,100,(2,2,2,2))
challenge

array([[[[33,  2],
         [35, 20]],

        [[56, 10],
         [ 8,  4]]],


       [[[41, 36],
         [57, 18]],

        [[24, 38],
         [56, 31]]]])

In [10]:
print(challenge.shape)
print(challenge.size)
challenge.ndim

(2, 2, 2, 2)
16


4

In [11]:
np.reshape(challenge,(1,16),'A')

array([[33,  2, 35, 20, 56, 10,  8,  4, 41, 36, 57, 18, 24, 38, 56, 31]])

In [12]:
np.reshape(challenge,(4,16), 'C')

ValueError: cannot reshape array of size 16 into shape (4,16)