In [13]:
import numpy as np

In [14]:
arr = np.random.randint(1,20,10)
arr

array([ 5,  1, 17, 13, 13,  9,  1,  2, 15, 11])

In [15]:
matrix = arr.reshape(2,5)
matrix

array([[ 5,  1, 17, 13, 13],
       [ 9,  1,  2, 15, 11]])

In [16]:
arr.max()

17

In [37]:
print(matrix.max(0))
print(matrix.max(1))

[ 9  1 17 15 13]
[17 15]


In [38]:
arr.argmax()

2

In [39]:
matrix.argmax(0)

array([1, 0, 0, 1, 0])

In [40]:
arr.min()

1

In [41]:
matrix.min(0)

array([ 5,  1,  2, 13, 11])

In [42]:
arr.argmin()

1

In [43]:
matrix.argmin(0)

array([0, 0, 1, 0, 1])

In [44]:
matrix.argmin(1)

array([1, 1])

In [46]:
arr.ptp()

16

In [47]:
matrix.ptp(0)

array([ 4,  0, 15,  2,  2])

In [62]:
arr.sort()

In [63]:
print(arr)
print(np.percentile(arr,50)) #median value taken out by percentile
print(np.median(arr))

[ 1  1  2  5  9 11 13 13 15 17]
10.0
10.0


In [64]:
print(matrix)
np.median(matrix, 0)

[[ 1  1  2  5  9]
 [11 13 13 15 17]]


array([ 6. ,  7. ,  7.5, 10. , 13. ])

In [65]:
np.std(arr)

5.728001396647874

In [66]:
np.var(arr)

32.81

In [67]:
np.mean(arr)

8.7

#### `Concatenation`

In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [77]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [78]:
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [79]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [82]:
b.T

array([[5],
       [6]])

In [83]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])