In [2]:
import numpy as np

``.copy()`` is a NumPy method which allows us to copy an array into another variabe in a way that at moment of modifying our new value-passed array, changes just occur in the new array and any modification happens in the original array.

In [3]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Let's take out a chunk of our original array.

In [4]:
array_cut = array[0:6]
array_cut

array([0, 1, 2, 3, 4, 5])

Converting our ``array_cut`` in an array of zeros.

In [5]:
array_cut[:] = 0
array_cut

array([0, 0, 0, 0, 0, 0])

In [6]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Now, we can observe that original array has been modified!. So imagine that our connected database would be modified forever just without using `.copy()`

In [7]:
array_copy = array.copy()
array_copy[:] = 100
print(array_copy)
print(array)

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]


Now, we can check that original array was not modified using the `.copy()` method, as happened when we edited the `array_cut`.

When we have a value-passed variable, info is stored in a different memory dict respect to original array, therefore if that new variable value changes, original array remains same. 

When it is by reference, the variable that is received as a parameter in the function points exactly to the same memory address as the original array, so if its values is modified within the function, the original variable is also modified.

<div style="text-align: center;">
    <img src="../imgs/np-pd.gif" alt="Alt Text" width="400" height="200">
</div>