In [23]:
import numpy as np

In [24]:
list = [1,2]

In [25]:
list*2

[1, 2, 1, 2]

In [26]:
arr = np.arange(0,10)
arr2 = arr.copy()

#### `Operations`

In [27]:
print(arr)
arr2 * 2

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

If a division between two numbers is invalid with one of the elements of the array, a `RuntimeWarning` is raised and indetermined result is replaced by an inf.

In [29]:
1 / arr2

/tmp/ipykernel_367/3854864060.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [30]:
arr2 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
arr ** arr2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [32]:
matrix = arr.reshape(2,5)
print(matrix)
matrix2 = matrix.copy()
print(matrix2.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


`Dot product` between a matrix A of dimension n * m and another matrix B of dimension m * n turns out in a n * n dimension matrix output. In this case, A is a 2x5 and B= A.T is a 5x2 matrix.

In [33]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [34]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])